//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsurance01.Models
{
   
    
    public partial class CarInfo01
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string emailAddress { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string carMake { get; set; }
        public string carModel { get; set; }
        public int carYear { get; set; }
        public int tickets { get; set; }
        public string dui { get; set; }
        public string coverage { get; set; }
        public System.DateTime removed { get; set; }
        public decimal carTotal { get; set; }
    }
}
